### ISSUE TITLE
Clean up appveyor build process 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#691]
Once #611 and all its little babies are taken care of, we can redo our horrid appveyor setup. Some ideas:
- [x] ditch nuget, since we don't use it in the instructions and it supports vcpkg
- [x] if possible, ditch the extra cmake path setting in the main CMakeLists.txt (APPVEYOR_DEPS)
- [x] get rid of manual dll downloads and the need to pass so many paths
- [ ] they support bash (WSL) now, there's no need for the awkward powershell hoops (only in the 2019 image, so not yet)
- [x] commit the yaml config file, so it's version tracked
- [x] recheck the built binaries still work as advertised
- [x] enable caching for vcpkg
- [x] enable choco caching for openssh
- [x] enable nuget caching securefile
- [x] More options are available once we use a bundled yml, so add:
```
skip_commits:
  # appveyor only searches for these in the first line by default
  message: /\[ci skip\]/
only_commits:
  files:
    - gemrb/**/*
    - cmake/**/*
    - windows/**/*
```
